apiVersion: apps/v1
kind: Deployment
metadata:
  name: javademo-deployment
  labels:
    app: javademoapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: javademoapp
  
  template:
    metadata:
      labels:
        app: javademoapp
    spec:
      containers:
      - name: javademoapp
        image: ptdevregistry.azurecr.io/springbootdemo:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 1024Mi
            cpu: 250m

        ports:
          - name: liveness-port
            containerPort: 8080
    
        livenessProbe:
          httpGet:
            path: /actuator/health  
            port: liveness-port    
          initialDelaySeconds: 150
          periodSeconds: 30

        startupProbe:
          httpGet:
            path: /actuator/health
            port: liveness-port        
          initialDelaySeconds: 120
          periodSeconds: 30
