apiVersion: v1
kind: Service
metadata:
  name: "javademo-api"
  labels:
    app: "javademoapp"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: "javademoapp"